--- #YAML:1.0
name:               Linux-Cgroups
version:            1.00
abstract:           Pure Perl interface to Linux Control Groups.
author:
    - Marian Marinov <HackMan>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
provides:
    Linux::Setns:
        file: lib/Linux/Cgroups.pm
        version: 1.00
requires:
    perl: 5.010001
no_index:
    directory:
        - t
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version: 1.4
resources:
    repository: https://github.com/hackman/Linux-Cgroups
    license: http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
